# https://support.crowdin.com/developer/configuration-file/
project_identifier: PROJECT_IDENTIFIER_CROWDIN
pull_request_title: New Crowdin updates  # Do not change this line
pull_request_labels:
  - do-not-merge  # Do not change this line
api_key: API_KEY_CROWDIN
base_path: ./
preserve_hierarchy: 1
files:
  # Update this to the correct extensions of your project
  - source: /content/en/_data/en/navigation.yml
    translation: /content/%two_letters_code%/_data/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
  - source: /content/en/_data/en/messages.yml
    translation: /content/%two_letters_code%/_data/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
  - source: /content/en/index.html
    translation: /content/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
  - source: /content/en/*.md
    translation: /content/%two_letters_code%/%original_file_name%
    ignore:
      - /content/en/_posts/**
      - /content/en/numcodecs_redirects/**
      - /content/en/slides.html
      - /content/en/slides/**
      - /content/en/slides/css/theme/**
      - /content/en/slides/plugin/markdown/**
    update_option: update_as_unapproved
  - source: /content/en/about/*.html
    translation: /content/%two_letters_code%/about/%original_file_name%
    update_option: update_as_unapproved
  - source: /content/en/adopters/*.md
    translation: /content/%two_letters_code%/adopters/%original_file_name%
    update_option: update_as_unapproved
  - source: /content/en/community/*.md
    translation: /content/%two_letters_code%/community/%original_file_name%
    update_option: update_as_unapproved
  - source: /content/en/conventions/*.md
    translation: /content/%two_letters_code%/conventions/%original_file_name%
    update_option: update_as_unapproved
  - source: /content/en/datasets/*.md
    translation: /content/%two_letters_code%/datasets/%original_file_name%
    update_option: update_as_unapproved
  - source: /content/en/implementations/*.md
    translation: /content/%two_letters_code%/implementations/%original_file_name%
    update_option: update_as_unapproved
  - source: /content/en/office-hours/*.md
    translation: /content/%two_letters_code%/office-hours/%original_file_name%
    update_option: update_as_unapproved
