project_identifier: PROJECT_IDENTIFIER_CROWDIN
api_key: API_KEY_CROWDIN
base_path: ./
preserve_hierarchy: 1
files:
  - source: /content/en/_config.yml
    translation: /content/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
  - source: /content/en/**/*.md
    translation: /content/%two_letters_code%/%original_file_name%
    ignore:
      - /content/en/README.md
      - /content/en/_posts/**
      - /content/en/numcodecs_redirects/**
      - /content/en/slides/**
      - /content/en/slides/plugin/**
      - /content/en/slides/theme/**
    update_option: update_as_unapproved
