name: Clean up
on:
  schedule:
    - cron: '0 0 * * FRI'  # Every Fridat at midnight
  workflow_dispatch:
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Clean Zarr translation repository
        uses: Scientific-Python-Translations/clean-up@main
        with:
          translations-repo: "Scientific-Python-Translations/zarr.dev-translations"
          translations-ref: "main"
          # These are provided by the Scientific Python Project and allow
          # automation with bots
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          token: ${{ secrets.TOKEN }}
