name: Check for "do-not-merge" label

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened]

jobs:
  check_do_not_merge_label:
    runs-on: ubuntu-latest

    steps:
      - name: Check for "do-not-merge" Label
        id: check_label
        # https://stackoverflow.com/a/71510189/992102
        if: contains(github.event.pull_request.labels.*.name, 'do-not-merge')
        run: |
          echo "DO NOT MERGE"
          exit 1
