name: Sync Content

on:
  schedule:
    - cron: '0 5 * * *'  # Daily at 5 am
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Zarr Content
        uses: Scientific-Python-Translations/content-sync@main
        with:
          source-repo: "zarr-developers/zarr-developers.github.io"
          source-folder: "zarr-developers.github.io"
          source-ref: "main"
          translations-repo: "Scientific-Python-Translations/zarr.dev-translations"
          translations-folder: "zarr.dev-translations/content/en"
          translations-ref: "main"
          # These are provided by the Scientific Python Project and allow
          # automation with bots
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          token: ${{ secrets.TOKEN }}
