name: Sync Translations
on:
  # schedule:
  #   - cron: '0 0 * * MON'  # Every Monday at midnight
  workflow_dispatch:
jobs:
  sync_translations:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Zarr translations
        uses: Scientific-Python-Translations/translations-sync@main
        with:
          crowdin-project: "Zarr.dev"
          source-repo: "zarr-developers/zarr-developers.github.io"
          source-path: "en/"
          source-ref: "main"
          translations-repo: "Scientific-Python-Translations/zarr.dev-translations"
          translations-path: "content/"
          translations-source-path: "content/en/"
          translations-ref: "main"
          translation-percentage: "90"
          approval-percentage: "0"
          use-precommit: "false"
          create-toml-file: "false"
          create-upstream-pr: "false"
          auto-merge: "false"
          # These are provided by the Scientific Python Project and allow
          # automation with bots
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          token: ${{ secrets.TOKEN }}
          crowdin-token: ${{ secrets.CROWDIN_TOKEN }}
